# vm-deployment.yaml
imports:
- path: vm-template.jinja

resources:
- name: vm-instance
  type: vm-template.jinja
  properties:
    zone: {{ properties['zone'] }}
    machineType: {{ properties['machineType'] }}
    sourceImage: {{ properties['sourceImage'] }}
    diskSizeGb: 10
