# vm-deployment.yaml
imports:
- path: vm-template.jinja

resources:
- name: vm-instance
  type: vm-template.jinja
  properties:
    zone: us-central1-a
    machineType: n1-standard-1
    sourceImage: projects/debian-cloud/global/images/family/debian-9
    diskSizeGb: 10